# Generated by Django 4.2.5 on 2023-09-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='preview',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='is_public',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='header',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
