# Generated by Django 4.2.5 on 2023-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='наименование')),
                ('category_description', models.CharField(max_length=200, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='в наличии')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='наименование')),
                ('product_description', models.CharField(max_length=200, verbose_name='описание продукта')),
                ('product_image', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('product_category', models.CharField(max_length=50, verbose_name='категория')),
                ('product_price', models.FloatField(verbose_name='цена')),
                ('product_date_creation', models.DateField(verbose_name='дата создания')),
                ('product_date_modification', models.DateField(verbose_name='дата последнего изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='в наличии')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_category', 'product_name', 'product_date_modification'),
            },
        ),
    ]
